apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-publisher-api
  namespace: rabbit-mq-applications
  labels:
    app: node-publisher-api
spec:
  replicas: 4 # Number of pod replicas
  selector:
    matchLabels:
      app: node-publisher-api
  template:
    metadata:
      labels:
        app: node-publisher-api
    spec:
      containers:
        - name: node-publisher-api
          image: node-publisher-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000 # Typical port for NestJS apps
            - containerPort: 5672 # RabbitMQ protocol port
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: ENV
              value: "prod"
            - name: MQ_TYPE
              value: publisher
            - name: RABBITMQ_HOST
              value: "rabbitmq.rabbitmq.svc.cluster.local"
            - name: RABBITMQ_USER
              value: "user"
            - name: RABBITMQ_PASSWORD
              value: "A5DGzuG3HeX48hwS"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: node-publisher-api-service
  namespace: rabbit-mq-applications
spec:
  type: ClusterIP
  selector:
    app: node-publisher-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
    - protocol: TCP
      port: 5672
      targetPort: 5672
